######################################################################
# Automatically generated by qmake (2.01a) to 24. maalis 09:24:08 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui webkit

# Input
HEADERS += webkitinfo.h
SOURCES += webkitinfo.cpp

maemo5 {
    target.path = /opt/qtinfo/bin
    INSTALLS += target
}
