######################################################################
# Automatically generated by qmake (2.01a) to 24. maalis 09:24:08 2011
######################################################################

include (../multipass.pri)

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core 

TARGET = bb10infolib

LIBS += -lbbplatform -lbbdevice

# Input
HEADERS += bb10infolib.h
SOURCES += bb10infolib.cpp

OTHER_FILES += \
    assets/qtinfo.svg \
    assets/qtinfo.png

