######################################################################
# Automatically generated by qmake (2.01a) to 24. maalis 09:24:08 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui declarative

# Input
HEADERS += qtquickinfo.h
SOURCES += qtquickinfo.cpp

maemo5 {
    target.path = /opt/qtinfo/bin
    INSTALLS += target
}
